language: node_js
version: 1.0
node_js:
  - '10'
  - '12'
before_script: npm run pre-build
script:
  - npm run build

jobs:
  include:
    - stage: npm release
      if: tag IS present
      node_js: '10'
      before_script:
        - npm run pre-build
        - chmod +x ./setupPackage.sh
      script: npm run build
      before_deploy: ./setupPackage.sh && cd lib
      deploy:
        provider: npm
        edge: true
        email: '$NPM_EMAIL'
        api_key: '$API_TOKEN'
        skip_cleanup: true
        on:
          tags: true